resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    shared:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 4
      ringBufferSizeInHalfOpenState: 2
      waitDurationInOpenState: 20s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.resilience4j.exception.BusinessException
  instances:
    helloWorld:
      baseConfig: default
      ringBufferSizeInClosedState: 4
      registerHealthIndicator: true
      recordExceptions:
        - java.lang.RuntimeException
    callOtherService:
      baseConfig: default
      ringBufferSizeInClosedState: 4
      registerHealthIndicator: true
      ignoreExceptions:
        # We need to ignore 4xx errors returned by the server as they are valid business case.
        - org.springframework.web.client.HttpClientErrorException
      recordExceptions:
        # We need to record all http errors
        - org.springframework.web.client.RestClientException
    myFeignClient:
      baseConfig: default
      ringBufferSizeInClosedState: 4
      registerHealthIndicator: true
      ignoreExceptions:
        - feign.FeignException.BadRequest
        - feign.FeignException.Unauthorized
        - feign.FeignException.Forbidden
        - feign.FeignException.NotFound
        - feign.FeignException.MethodNotAllowed
        - feign.FeignException.NotAcceptable
        - feign.FeignException.Conflict
        - feign.FeignException.Gone
        - feign.FeignException.UnsupportedMediaType
        - feign.FeignException.TooManyRequests
        - feign.FeignException.UnprocessableEntity
      recordExceptions:
        - java.net.SocketTimeoutException
        - java.net.ConnectException
        - feign.FeignException.InternalServerError
        - feign.FeignException.NotImplemented
        - feign.FeignException.BadGateway
        - feign.FeignException.GatewayTimeout
        - feign.FeignException.ServiceUnavailable
        - feign.RetryableException

management:
  health:
    status:
      http-mapping:
        DOWN: 200

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

#info:
#  name: ${spring.application.name}
#  description: resilience4j demo
#  environment: ${spring.profiles.active}
#  version: 0.0.1

management.metrics.tags.application: harish-demo
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true